name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.0' # The Go version to download (if necessary) and use.

      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.37.2

      - name: build
        run: task build

      - name: version
        run: echo "verion=$(./bin/invoiceling --version | cut -d' ' -f 3)" >> $GITHUB_OUTPUT
        id: version

      - name: build artifacts
        run: task build-linux && task build-windows && task build-darwin

      - name: Create tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ github.token }}
          custom_tag:  ${{ steps.version.outputs.version}}

      - name: Build changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: '.github/changelog-configuration.json'
          fromTag: ${{ steps.tag.outputs.previous_tag}}
          toTag: ${{ steps.tag.outputs.new_tag}}
          failOnError: true

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.github_release.outputs.changelog }}
          files: |
            ./bin/invoiceling.darwin-amd64.tar.gz
            ./bin/invoiceling.darwin-arm64.tar.gz
            ./bin/invoiceling.linux-amd64.tar.gz
            ./bin/invoiceling.windows-amd64.tar.gz
